name: Nix derivation checks

on:
  pull_request:
    paths: ["mix.lock"]
  workflow_dispatch:

jobs:
  auto-update-nix-hash:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Auto update Nix hash
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix run .#update-hash | tee nix/hash
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update Nix hash of Mix deps'
